export const BooksActionTypes = {
  GET_BOOKS_START: 'GET_BOOKS_START',
  GET_BOOKS_FINISH: 'GET_BOOKS_FINISH',
  GET_BOOKS_ERROR: 'GET_BOOKS_ERROR',
  DELETE_BOOKS: 'DELETE_BOOKS',
  LIKE_BOOK: 'LIKE_BOOK',
} as const;
